services:
  llm-service:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - /home/darkangel/ai-light-show/.ollama_data:/root/.ollama
    restart: unless-stopped
    command: serve
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"

volumes:
  ollama:

